version: "3"
services:
  web:
    image: docker-node-twitook
    build: .
    command: "npm start"
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"
    restart: unless-stopped
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - twitookmongodata:/data/db
volumes:
  twitookmongodata:
